"""add student unique register dob and father name

Revision ID: ba33817d72db
Revises: c7773cb5202c
Create Date: 2026-07-23 18:46:09.523703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba33817d72db'
down_revision = 'c7773cb5202c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('father_name', sa.String(length=150), nullable=True))
        batch_op.create_unique_constraint(None, ['register_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('father_name')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('register_number')

    # ### end Alembic commands ###
