"""add mentor and coordinator fields

Revision ID: c7773cb5202c
Revises: 07edb936a089
Create Date: 2026-07-23 15:10:53.259532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7773cb5202c'
down_revision = '07edb936a089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('od', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_coordinator_id', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('applied_on',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['event_coordinator_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentor_id', sa.Integer(), nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('leave_balance',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'20'"))
        batch_op.drop_constraint(batch_op.f('fk_faculty'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'class_group', ['class_group_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['mentor_id'], ['id'])
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['faculty_id'], ['id'])
        batch_op.drop_column('register_number')

    op.drop_table('faculty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_number', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_faculty'), 'faculty', ['faculty_id'], ['id'])
        batch_op.alter_column('leave_balance',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'20'"))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('mentor_id')

    with op.batch_alter_table('od', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('applied_on',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('event_coordinator_id')

    op.create_table('faculty',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
