"""Add faculty_id to user

Revision ID: ffab3e36b707
Revises: c0bc29e75c6d
Create Date: 2025-09-18 10:48:22.607321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffab3e36b707'
down_revision = 'c0bc29e75c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_table('users')
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.alter_column('requested_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('leave_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('leave_ibfk_4'), type_='foreignkey')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('od', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['faculty_id'], ['id'])
        batch_op.create_foreign_key(None, 'class_group', ['class_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('faculty_id')

    with op.batch_alter_table('od', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('leave_ibfk_4'), 'user', ['reviewed_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('leave_ibfk_3'), 'user', ['user_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('requested_by',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.ENUM('STUDENT', 'FACULTY', 'HOD'), nullable=False),
    sa.Column('class_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('leave_balance', mysql.INTEGER(), server_default=sa.text("'12'"), autoincrement=False, nullable=True),
    sa.Column('faculty_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('leave_requests',
    sa.Column('request_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.ENUM('LEAVE', 'OD'), nullable=False),
    sa.Column('reason', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('faculty_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hod_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.user_id'], name=op.f('leave_requests_ibfk_2')),
    sa.ForeignKeyConstraint(['hod_id'], ['users.user_id'], name=op.f('leave_requests_ibfk_3')),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], name=op.f('leave_requests_ibfk_1')),
    sa.PrimaryKeyConstraint('request_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
