"""add otp token table

Revision ID: 07edb936a089
Revises: 2f6d0e7a9c31
Create Date: 2026-07-20 21:04:24.873816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07edb936a089'
down_revision = '2f6d0e7a9c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_token', schema=None) as batch_op:
        batch_op.create_index('ix_otp_token_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_otp_token_user_id_otp', ['user_id', 'otp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_token', schema=None) as batch_op:
        batch_op.drop_index('ix_otp_token_user_id_otp')
        batch_op.drop_index('ix_otp_token_expires_at')

    op.drop_table('otp_token')
    # ### end Alembic commands ###

